services:
  - type: web
    name: income-tracker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn finance_tracker.wsgi
    preDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: income-tracker-b1fz.onrender.com
