services:
  - type: web
    name: income-tracker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python manage.py migrate
      gunicorn finance_tracker.wsgi
      python manage.py migrate && gunicorn finance_tracker.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: income-tracker-b1fz.onrender.com
        